[theme]
primaryColor = "#4CAF50"
backgroundColor = "#0f2027"
secondaryBackgroundColor = "#203a43"
textColor = "#fafafa"
font = "sans serif"

[server]
headless = true
enableCORS = false
port = 8501

[runner]
magicEnabled = false
